// Textos da página "Província e cidades" (Fase 4b, B4). Todos os rótulos, títulos e
// notas em {pt, en} — NENHUM número literal de dado aqui: anos, contagens, bases de
// índice e unidades de medida entram por {marcadores} preenchidos pela página a partir
// de data/processed/. Os únicos algarismos que sobram são identificadores (seção §,
// ADR, emenda, DOI, ano de citação de autor), não quantidades. CLAUDE.md §6/§10.
export const TEXTOS = {
  pt: {
    kicker: "Província e cidades",
    titulo: "Quem cresceu, quando, e o que ainda não sabemos",
    lead: "A única unidade que o codificador do INE oferece para a Cidade de Tete é o distrito inteiro; a vila de Moatize não tem limite administrativo aberto e sua população só existe como estimativa de grade. Escolha uma unidade para ver os censos, a projeção e o contexto econômico.",

    segmentado_unidade_rotulo: "Unidade",
    unidade_provincia: "Província de Tete",
    unidade_tete: "Cidade de Tete",
    unidade_moatize_distrito: "Distrito de Moatize",
    unidade_moatize_vila: "Vila de Moatize",
    unidade_mocambique: "Moçambique (referência)",

    kpi_ultimo_censo_rotulo: "Último censo com dado",
    kpi_ultimo_censo_nota_padrao: "Contagem do recenseamento de {ano}, via HDX COD-PS.",
    kpi_ultimo_censo_nota_vila: "Estimativa de grade (GRID3 v1.1), não contagem — variante-teto sem peso de construído (ADR 0017); ver nota completa em Metodologia.",
    kpi_projecao_rotulo: "Projeção {ano} (modelada)",
    kpi_projecao_rotulo_sem_ano: "Projeção (modelada)",
    kpi_projecao_nota: "Projeção institucional do INE (HDX COD-PS, vintage {ano}) — não é recontagem.",
    kpi_projecao_indisponivel: "Sem projeção publicada para esta unidade.",
    kpi_cagr_rotulo_intervalo: "CAGR {intervalo}",
    kpi_cagr_rotulo_sem_intervalo: "CAGR",
    kpi_cagr_sem_dado: "Sem CAGR: um único ano não define ritmo.",
    kpi_cagr_vila_nota: "A Vila de Moatize tem um único ano ({ano}): nenhum CAGR é calculável, por construção — não é um dado ausente, é uma medição impossível com um ponto só.",
    kpi_mini_serie_rotulo: "População",

    fig1_titulo: "População e censos, {inicio}–{fim}",
    fig1_modo_rotulo: "Escala",
    fig1_modo_absoluto: "Valores absolutos",
    fig1_modo_indice: "Índice",
    fig1_subtitulo_absoluto: "Cascata local em valores absolutos ({unidade}): Cidade de Tete, Distrito de Moatize e Vila de Moatize, na mesma escala linear. Província e Moçambique ficam no modo Índice, onde não achatam as unidades locais. A unidade escolhida vem em traço grosso; marcadores vazados = nível de fonte B ou C; o trecho final tracejado é projeção modelada, não recontagem.",
    fig1_subtitulo_provincia: "Província de Tete em valores absolutos ({unidade}), sozinha na escala: com as unidades locais no mesmo eixo, elas ficariam coladas no zero. Para comparar a Província com Tete e Moatize, use o modo Índice. Marcadores vazados = nível de fonte B ou C; trecho final tracejado = projeção modelada.",
    fig1_subtitulo_indice: "Cada unidade dividida pelo seu primeiro censo com dado; eixo em {unidade}. Permite comparar o ritmo das unidades locais com a Província e com Moçambique sem que a escala absoluta achate as menores. Marcadores vazados = nível de fonte B ou C; trecho final tracejado = projeção modelada.",
    fig1_base_indice: "Base do índice por unidade, lida do nome da variável no CSV: {lista}. Bases diferentes significam que as curvas partem de anos diferentes; o que se compara é a inclinação, não o nível.",
    fig1_base_item: "{unidade} — {ano}",
    fig1_fonte: "data/processed/demografia_serie_1997_2025.csv (populacao_total_residente e indice_base_*); marcos de data/app/marcos.json",
    fig1_metodo: "Leitura direta do CSV, sem recálculo no front-end — o índice também é lido pronto do CSV. Selo e nível de cada ponto vêm da própria linha; o selo da figura é o pior entre os selos plotados (§10).",
    fig1_nota_moatize_vila: "A Vila de Moatize aparece só como ponto único em {ano} (modelada, GRID3) — sem trecho de linha, porque não há segundo ponto para ligar.",
    ver_tabela_legenda_fig1: "Tabela de população e índice por unidade e ano",
    tab_col_indice: "Índice",

    fig2_titulo: "Carvão, produção e luz — mesmo eixo, {inicio}–{fim}",
    fig2_subtitulo: "Três painéis empilhados com o mesmo eixo de tempo e escalas próprias — não é eixo duplo. Faixas sombreadas alternadas: fases da periodização analítica (§2); linhas verticais finas: marcos pontuais (concessão, licença, operação, saída). Passe o cursor num painel para ver o mesmo ano nos três.",
    fig2_painel_preco_titulo: "Preço do carvão, World Bank CMO",
    fig2_painel_producao_titulo: "Produção das minas",
    fig2_painel_luz_titulo: "Luz noturna somada — recorte Tete–Moatize",
    fig2_painel_unidade: "({unidade})",
    fig2_legenda_fases: "Fases (faixas)",
    fig2_legenda_marcos: "Marcos (linhas finas)",
    fig2_fonte: "World Bank Commodity Markets Observatory (preço); Vale/Vulcan/ICVL via SEC EDGAR (produção); NPP-VIIRS-like, Chen, Yu et al. (2021), Harvard Dataverse DOI 10.7910/DVN/YGIVCD (luz)",
    fig2_metodo: "Preço e luz lidos diretamente do CSV. A luz noturna é somada dentro do retângulo fixo da área de estudo (Emenda E6) — inclui Tete, Moatize e a mina; não é um recorte só da cidade.",
    fig2_luz_aviso: "Atenção: \"{rotulo}\" é um retângulo fixo que contém a Cidade de Tete, a vila de Moatize e a mina — a luz somada aqui não é só da cidade.",
    fig2_luz_controle_rotulo: "Luz: comparação",
    fig2_luz_controle_so_tete: "Só Tete–Moatize",
    fig2_luz_controle_com_controles: "Com cidades-controle",
    fig2_producao_vazio_frase: "Série de produção ainda não publicada: a coleta nos relatórios da Vale na SEC aguarda autorização de acesso.",
    fig2_producao_vazio_frase_generica: "Série de produção ainda não publicada; o motivo de cada mina está no tooltip de fonte, acima.",
    fig2_producao_vazio_lista: "Variáveis previstas:",
    fig2_producao_prov_rotulo: "Fonte e motivo técnico, por mina",
    ausencias_prov_rotulo: "fonte e motivo técnico",
    fig2_producao_vazio_rodape: "O painel passa a desenhar a série sozinho quando o CSV de produção tiver valor numérico.",
    ver_tabela_legenda_fig2: "Tabela de preço do carvão e luz noturna somada, por ano",

    fig3_titulo: "Contas regionais — contexto, não núcleo",
    fig3_aviso: "Estas {n} linhas vêm do Folheto Provincial de Tete do INE e são todas de nível C (§4.0): sem licença de reuso localizável no documento, sem reprocessador aberto alternativo. Ficam aqui como contexto de leitura — nenhuma conclusão do estudo se apoia nelas.",
    fig3_fonte: "INE, Folheto Provincial de Tete (via Wayback Machine); fonte por linha no tooltip de cada valor",
    fig3_col_unidade: "Unidade",
    fig3_col_ano: "Ano",
    fig3_col_variavel: "Variável",
    fig3_col_valor: "Valor",

    bloco_ausencias_titulo: "O que não existe e por quê",
    bloco_ausencias_intro: "Lista gerada de data/processed/csv/demografia_contexto_nao_nucleo.csv e das linhas \"não disponível\" de data/processed/economia/producao_moatize_anual.csv — nada aqui foi escrito à mão.",
    bloco_ausencias_col_item: "Item",
    bloco_ausencias_col_motivo: "Motivo",

    // Nomes legíveis das variáveis dos CSV (chave = `variavel` do CSV). Variável ausente
    // do mapa aparece com o nome cru, para não esconder nada que o pipeline publique.
    variaveis: {
      populacao_total_residente: "População residente",
      producao_carvao_total: "Produção de carvão, total",
      producao_carvao_metalurgico: "Produção de carvão metalúrgico",
      producao_carvao_termico: "Produção de carvão térmico",
      capacidade_nominal: "Capacidade nominal",
      empregados_mocambique: "Empregados em Moçambique",
      taxa_crescimento_pib_real: "Crescimento real do PIB",
      pib_per_capita_usd: "PIB per capita",
      pib_percentual_pib_nacional: "Participação no PIB nacional",
      inflacao_media: "Inflação média anual",
      inflacao_acumulada: "Inflação acumulada no ano",
    },
    // Unidades de medida por idioma (chave = `unidade_medida` do CSV).
    unidades_medida: { percentual: "%", USD: "USD", pessoas: "pessoas", "%/ano": "%/ano", "índice (base=100)": "índice (base=100)" },
    // Grafia das unidades geográficas das contas regionais (o CSV do INE vem sem acento).
    unidades_geo: { "Provincia de Tete": "Província de Tete", Mocambique: "Moçambique" },

    // Tabelas "Ver tabela" e tooltips dos gráficos: proveniência célula a célula.
    tab_col_populacao: "População",
    tab_sem_linha: "sem linha no CSV",
    selo_rotulos: { observado: "observado", interpolado: "interpolado", modelado: "modelado" },
    nivel_rotulo_prefixo: "nível",
    preco_australia: "Austrália",
    preco_africa_do_sul: "África do Sul",
    luz_unidade_nao_declarada: "soma de radiância, unidade do produtor",
    luz_metodo_linha: "Soma dos valores de radiância dos pixels dentro de: {geometria} (coluna soma_radiancia).",
    luz_nota_janela_fora: "Ano fora da janela homogênea declarada pelo pipeline (EMENDA E4, docs/DESENHO_FASE3.md).",
    luz_nota_janela_dentro: "Ano dentro da janela homogênea declarada pelo pipeline (EMENDA E4, docs/DESENHO_FASE3.md).",
    tooltip_sem_linha: "sem linha no CSV para este ponto",

    esqueleto_aria: "Carregando dados da página Província e cidades",
    unidade_desconhecida: "Unidade sem dados nesta série.",
  },

  en: {
    kicker: "Province and cities",
    titulo: "Who grew, when, and what we still don't know",
    lead: "The only unit the INE coder offers for Tete City is the whole district; Moatize town has no open administrative boundary and its population only exists as a grid estimate. Choose a unit to see the censuses, the projection, and the economic context.",

    segmentado_unidade_rotulo: "Unit",
    unidade_provincia: "Tete Province",
    unidade_tete: "Tete City",
    unidade_moatize_distrito: "Moatize District",
    unidade_moatize_vila: "Moatize Town",
    unidade_mocambique: "Mozambique (reference)",

    kpi_ultimo_censo_rotulo: "Latest census with data",
    kpi_ultimo_censo_nota_padrao: "Count from the {ano} census, via HDX COD-PS.",
    kpi_ultimo_censo_nota_vila: "Grid estimate (GRID3 v1.1), not a count — ceiling variant with no built-up weighting (ADR 0017); full note in Methodology.",
    kpi_projecao_rotulo: "{ano} projection (modeled)",
    kpi_projecao_rotulo_sem_ano: "Projection (modeled)",
    kpi_projecao_nota: "INE institutional projection (HDX COD-PS, {ano} vintage) — not a recount.",
    kpi_projecao_indisponivel: "No published projection for this unit.",
    kpi_cagr_rotulo_intervalo: "CAGR {intervalo}",
    kpi_cagr_rotulo_sem_intervalo: "CAGR",
    kpi_cagr_sem_dado: "No CAGR: a single year does not define a rate.",
    kpi_cagr_vila_nota: "Moatize Town has a single year ({ano}): no CAGR is computable, by construction — this is not a missing datum, it is an impossible measurement with only one point.",
    kpi_mini_serie_rotulo: "Population",

    fig1_titulo: "Population and censuses, {inicio}–{fim}",
    fig1_modo_rotulo: "Scale",
    fig1_modo_absoluto: "Absolute values",
    fig1_modo_indice: "Index",
    fig1_subtitulo_absoluto: "Local cascade in absolute values ({unidade}): Tete City, Moatize District and Moatize Town on the same linear scale. Province and Mozambique are in Index mode, where they do not flatten the local units. The chosen unit is drawn thick; hollow markers = source level B or C; the dashed final stretch is a modeled projection, not a recount.",
    fig1_subtitulo_provincia: "Tete Province in absolute values ({unidade}), alone on the scale: with the local units on the same axis they would be pressed against zero. To compare the Province with Tete and Moatize, use Index mode. Hollow markers = source level B or C; dashed final stretch = modeled projection.",
    fig1_subtitulo_indice: "Each unit divided by its first census with data; axis in {unidade}. This lets the local units be compared with the Province and Mozambique without the absolute scale flattening the smaller ones. Hollow markers = source level B or C; dashed final stretch = modeled projection.",
    fig1_base_indice: "Index base by unit, read from the variable name in the CSV: {lista}. Different bases mean the curves start in different years; what is compared is the slope, not the level.",
    fig1_base_item: "{unidade} — {ano}",
    fig1_fonte: "data/processed/demografia_serie_1997_2025.csv (populacao_total_residente and indice_base_*); marks from data/app/marcos.json",
    fig1_metodo: "Direct read from the CSV, no recomputation in the front end — the index is also read ready-made from the CSV. Each point's stamp and level come from its own row; the figure's stamp is the worst of the plotted stamps (§10).",
    fig1_nota_moatize_vila: "Moatize Town shows only as a single point in {ano} (modeled, GRID3) — no line segment, because there is no second point to connect.",
    ver_tabela_legenda_fig1: "Population and index table by unit and year",
    tab_col_indice: "Index",

    fig2_titulo: "Coal, output and light — same axis, {inicio}–{fim}",
    fig2_subtitulo: "Three stacked panels with the same time axis and their own scales — not a dual axis. Alternating shaded bands: phases of the analytical periodization (§2); thin vertical lines: point events (concession, licence, operation, exit). Hover one panel to see the same year in all three.",
    fig2_painel_preco_titulo: "Coal price, World Bank CMO",
    fig2_painel_producao_titulo: "Mine output",
    fig2_painel_luz_titulo: "Summed night-time light — Tete–Moatize clip",
    fig2_painel_unidade: "({unidade})",
    fig2_legenda_fases: "Phases (bands)",
    fig2_legenda_marcos: "Events (thin lines)",
    fig2_fonte: "World Bank Commodity Markets Observatory (price); Vale/Vulcan/ICVL via SEC EDGAR (output); NPP-VIIRS-like, Chen, Yu et al. (2021), Harvard Dataverse DOI 10.7910/DVN/YGIVCD (light)",
    fig2_metodo: "Price and light read directly from the CSV. Night-time light is summed inside the study area's fixed rectangle (Amendment E6) — it includes Tete, Moatize and the mine, not only the city.",
    fig2_luz_aviso: "Note: \"{rotulo}\" is a fixed rectangle containing Tete City, Moatize town and the mine — the summed light here is not the city's alone.",
    fig2_luz_controle_rotulo: "Light: comparison",
    fig2_luz_controle_so_tete: "Tete–Moatize only",
    fig2_luz_controle_com_controles: "With control cities",
    fig2_producao_vazio_frase: "Output series not yet published: collection from Vale's SEC filings is awaiting access authorisation.",
    fig2_producao_vazio_frase_generica: "Output series not yet published; each mine's reason is in the source tooltip above.",
    fig2_producao_vazio_lista: "Planned variables:",
    fig2_producao_prov_rotulo: "Source and technical reason, by mine",
    ausencias_prov_rotulo: "source and technical reason",
    fig2_producao_vazio_rodape: "The panel will draw the series by itself once the output CSV has a numeric value.",
    ver_tabela_legenda_fig2: "Coal price and summed night-time light table, by year",

    fig3_titulo: "Regional accounts — context, not core",
    fig3_aviso: "These {n} rows come from the INE's Tete Provincial Leaflet and are all level C (§4.0): no reusable licence found in the document, no alternative open reprocessor. They are shown here as reading context — no conclusion of the study rests on them.",
    fig3_fonte: "INE, Tete Provincial Leaflet (via Wayback Machine); per-row source in each value's tooltip",
    fig3_col_unidade: "Unit",
    fig3_col_ano: "Year",
    fig3_col_variavel: "Variable",
    fig3_col_valor: "Value",

    bloco_ausencias_titulo: "What doesn't exist, and why",
    bloco_ausencias_intro: "List generated from data/processed/csv/demografia_contexto_nao_nucleo.csv and the \"not available\" rows of data/processed/economia/producao_moatize_anual.csv — nothing here was hand-written.",
    bloco_ausencias_col_item: "Item",
    bloco_ausencias_col_motivo: "Reason",

    variaveis: {
      populacao_total_residente: "Resident population",
      producao_carvao_total: "Coal output, total",
      producao_carvao_metalurgico: "Metallurgical coal output",
      producao_carvao_termico: "Thermal coal output",
      capacidade_nominal: "Nameplate capacity",
      empregados_mocambique: "Employees in Mozambique",
      taxa_crescimento_pib_real: "Real GDP growth",
      pib_per_capita_usd: "GDP per capita",
      pib_percentual_pib_nacional: "Share of national GDP",
      inflacao_media: "Average annual inflation",
      inflacao_acumulada: "Year-to-date inflation",
    },
    unidades_medida: { percentual: "%", USD: "USD", pessoas: "people", "%/ano": "%/year", "índice (base=100)": "index (base=100)" },
    unidades_geo: { "Provincia de Tete": "Tete Province", Mocambique: "Mozambique" },

    tab_col_populacao: "Population",
    tab_sem_linha: "no CSV row",
    selo_rotulos: { observado: "observed", interpolado: "interpolated", modelado: "modeled" },
    nivel_rotulo_prefixo: "level",
    preco_australia: "Australia",
    preco_africa_do_sul: "South Africa",
    luz_unidade_nao_declarada: "summed radiance, producer's unit",
    luz_metodo_linha: "Sum of pixel radiance values inside: {geometria} (column soma_radiancia).",
    luz_nota_janela_fora: "Year outside the homogeneous window declared by the pipeline (AMENDMENT E4, docs/DESENHO_FASE3.md).",
    luz_nota_janela_dentro: "Year inside the homogeneous window declared by the pipeline (AMENDMENT E4, docs/DESENHO_FASE3.md).",
    tooltip_sem_linha: "no CSV row for this point",

    esqueleto_aria: "Loading the Province and cities page data",
    unidade_desconhecida: "Unit with no data in this series.",
  },
};

// Ordem de exibição do Segmentado de unidade (província → cidade → distrito → vila).
// `local: true` marca a cascata local que a Figura 1 mostra em valores absolutos.
export const UNIDADES_CASCATA = [
  { chave: "provincia", csv: "Província de Tete", rotuloId: "unidade_provincia", local: false },
  { chave: "tete", csv: "Cidade de Tete", rotuloId: "unidade_tete", local: true },
  { chave: "moatize_distrito", csv: "Distrito de Moatize", rotuloId: "unidade_moatize_distrito", local: true },
  { chave: "moatize_vila", csv: "Vila de Moatize", rotuloId: "unidade_moatize_vila", local: true },
];

export const UNIDADE_REFERENCIA = { chave: "mocambique", csv: "Moçambique", rotuloId: "unidade_mocambique", local: false };

// Tipos de marco (data/app/marcos.json, campo `tipo`) desenhados como linha fina na
// Figura 2 — os que o subtítulo nomeia. Datas e rótulos vêm do JSON.
export const TIPOS_MARCO_FIG2 = ["concessao", "licenca", "operacao", "saida"];
